<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Independent from TargetFrameWorks-->
  <ItemGroup>

    <!-- Demo Apps -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />

    <!-- Main dependencies -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />

    <!-- Tests -->
  </ItemGroup>
</Project>
