<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Independent from TargetFrameWorks-->
  <ItemGroup>
    <!-- Demo Apps -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.2" />
    <PackageVersion Include="LoxSmoke.DocXml" Version="3.9.0" />
    <!-- Main dependencies -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components" Version="5.0.0-preview.26036.2" />
    <!-- Shared dependencies -->
    <PackageVersion Include="Markdig.Signed" Version="0.44.0" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.162" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0-1.final" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <PackageVersion Include="Microsoft.VisualStudioEng.MicroBuild.Core" Version="1.0.0" />
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="5.9.3" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.13.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="3.12.0-beta1.25155.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.2" />
    <!-- Tests -->
    <PackageVersion Include="bunit" Version="2.5.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>