<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Documentation\Home.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Documentation\Components\FloattingButton\FloatingButton.md" />
    <EmbeddedResource Include="Documentation\Home.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Core\FluentUI.Blazor.Community.Components.csproj" />
    <ProjectReference Include="..\..\Tools\FluentUI.Demo.DocViewer\FluentUI.Demo.DocViewer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\" />
  </ItemGroup>

</Project>
