namespace FluentUI.Blazor.Community.Components.Enums;

/// <summary>
/// Specifies the severity level of a log message for console output.
/// </summary>
/// <remarks>Use this enumeration to categorize log messages by importance, enabling filtering and management of
/// console log output. The levels range from detailed tracing information to critical errors, allowing developers to
/// control the verbosity of logging according to their needs.</remarks>
public enum ConsoleLevel
{
    /// <summary>
    /// Gets or sets the tracing level for the application, which determines the amount of detail logged during
    /// execution.
    /// </summary>
    /// <remarks>The Trace property can be used to control the verbosity of logging output, allowing
    /// developers to adjust the level of detail based on the needs of debugging or monitoring. Common levels include
    /// 'Error', 'Warning', 'Info', and 'Verbose'.</remarks>
    Trace,

    /// <summary>
    /// Specifies the debug output level for the application.
    /// </summary>
    /// <remarks>Use this value to control the verbosity of debug messages generated by the application.
    /// Adjusting the debug level can help with troubleshooting by providing more or less detailed diagnostic
    /// information, depending on the needs of the developer or support personnel.</remarks>
    Debug,

    /// <summary>
    /// Provides information related to the current context or operation.
    /// </summary>
    /// <remarks>This property may contain various types of information depending on the implementation.
    /// Ensure to check the type of information it holds before usage.</remarks>
    Information,

    /// <summary>
    /// Represents a warning message that indicates a potential issue or important information that should be noted.
    /// </summary>
    /// <remarks>Warnings are typically used to alert users about conditions that may not be errors but could
    /// lead to unexpected behavior if not addressed. It is important to review and consider the implications of the
    /// warning before proceeding.</remarks>
    Warning,

    /// <summary>
    /// Represents an error that occurs during application execution.
    /// </summary>
    /// <remarks>This type encapsulates information about the error, including its message and any associated
    /// data. It is used to provide detailed error information to the caller, enabling better error handling and
    /// debugging.</remarks>
    Error,

    /// <summary>
    /// Indicates a critical level of importance or urgency.
    /// </summary>
    /// <remarks>Use this value to designate operations or resources that require immediate attention or have
    /// the highest priority. Assigning a critical level may affect processing order or resource allocation in systems
    /// that support prioritization.</remarks>
    Critical
}
