#pragma checksum "D:\TFS\Personnels\Microsoft\src\Core\_Imports.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "e373b6f66a7ae5f3bb24ca90c20a74cbe0cd17d248bd8dc28ffc9a04201c3ecd"
// <auto-generated/>
#pragma warning disable 1591
namespace FluentUI.Blazor.Community.Components
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,43) "D:\TFS\Personnels\Microsoft\src\Core\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,48) "D:\TFS\Personnels\Microsoft\src\Core\_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,62) "D:\TFS\Personnels\Microsoft\src\Core\_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Icons.Regular

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,58) "D:\TFS\Personnels\Microsoft\src\Core\_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class _Imports : object
    #nullable disable
    {
        #pragma warning disable 1998
        protected void Execute()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
