#pragma checksum "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "57ce9d249363cb5a1c050c77b610eeffde2a6abf4e6fb6784945819610813f72"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,48) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FluentUI.Blazor.Community.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,43) "E:\fluentui-blazor-community-extensions\src\Core\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,48) "E:\fluentui-blazor-community-extensions\src\Core\_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentCxFloatingButton : 
#nullable restore
#line (2,11)-(2,23) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FluentButton

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (4,2)-(6,1) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
if (IsVisible)
{

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentButton>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (6,19)-(6,29) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormAction

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (6,32)-(6,42) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormAction

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (7,19)-(7,39) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IReadOnlyDictionary<global::System.String, global::System.Object>>(
#nullable restore
#line (7,42)-(7,62) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (8,19)-(8,29) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Appearance

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.ButtonAppearance?>(
#nullable restore
#line (8,32)-(8,42) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Appearance

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (9,19)-(9,28) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
AutoFocus

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (9,31)-(9,40) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
AutoFocus

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (10,19)-(10,34) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
BackgroundColor

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (10,37)-(10,52) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
BackgroundColor

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(6, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (11,19)-(11,31) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
ChildContent

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (11,34)-(11,46) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
ChildContent

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(7, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (12,19)-(12,24) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (12,27)-(12,32) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Class

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(8, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (13,19)-(13,24) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Color

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (13,27)-(13,32) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Color

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(9, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (14,19)-(14,23) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Data

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Object>(
#nullable restore
#line (14,26)-(14,30) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Data

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(10, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (15,19)-(15,27) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Disabled

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (15,29)-(15,37) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Disabled

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(11, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (16,19)-(16,30) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormEncType

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (16,33)-(16,44) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormEncType

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(12, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (17,19)-(17,25) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormId

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (17,28)-(17,34) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormId

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(13, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (18,19)-(18,26) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
IconEnd

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (18,29)-(18,36) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
IconEnd

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(14, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (19,19)-(19,28) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
IconStart

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (19,31)-(19,40) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
IconStart

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(15, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (20,19)-(20,21) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Id

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (20,24)-(20,26) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(16, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (21,19)-(21,26) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Loading

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (21,28)-(21,35) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Loading

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(17, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (22,19)-(22,29) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormMethod

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (22,32)-(22,42) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormMethod

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(18, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (23,19)-(23,23) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Name

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (23,26)-(23,30) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(19, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (24,19)-(24,33) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormNoValidate

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (24,36)-(24,50) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FormNoValidate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(20, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (25,19)-(25,26) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
OnClick

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (25,29)-(25,36) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
OnClick

#line default
#line hidden
#nullable disable
            )));
            __builder.AddComponentParameter(21, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (26,19)-(26,26) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Padding

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (26,29)-(26,36) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Padding

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(22, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (27,19)-(27,25) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Margin

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (27,28)-(27,34) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Margin

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(23, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (28,19)-(28,27) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Required

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (28,29)-(28,37) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Required

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(24, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (29,19)-(29,34) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
StopPropagation

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (29,36)-(29,51) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
StopPropagation

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(25, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (30,19)-(30,24) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (30,27)-(30,40) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
InternalStyle

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(26, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (31,19)-(31,24) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Title

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (31,27)-(31,32) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Title

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(27, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (32,19)-(32,23) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Type

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.ButtonType?>(
#nullable restore
#line (32,26)-(32,30) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Type

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(28, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentButton.
#nullable restore
#line (33,19)-(33,24) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (33,27)-(33,32) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
Value

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseComponent();
#nullable restore
#line (34,1)-(35,1) "E:\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
