#pragma checksum "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "c63f5265c750f1122162591bd5f009c3206d869a26fc294ae0f0d5c505f1fbd2"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,48) "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FluentUI.Blazor.Community.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,43) "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,48) "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentCxFloatingButton : 
#nullable restore
#line (2,11)-(2,23) "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
FluentButton

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (4,2)-(8,1) "D:\Programmierung\fluentui-blazor-community-extensions\src\Core\Components\FloatingButton\FluentCxFloatingButton.razor"
if (IsVisible)
{
    base.BuildRenderTree(__builder);
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
