<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <SignAssembly>False</SignAssembly>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(SolutionDir).generated</CompilerGeneratedFilesOutputPath>

  </PropertyGroup>



  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components">
      <IncludeAssets>runtime; build; native; compile</IncludeAssets>
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.TypeScript.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <XmlFiles Include="$(ProjectDir)bin\$(Configuration)\net10.0\*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(XmlFiles)" DestinationFolder="$(SolutionDir)examples\tools\FluentUI.Demo.DocApiGen" />
  </Target>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Components.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- Resources Localization  -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <EmbeddedResource Update="Localization\LanguageResource.resx">
      <Public>true</Public>
      <OmitGetResourceString>true</OmitGetResourceString>
      <AsConstants>true</AsConstants>
      <NoWarn>CS1591</NoWarn>
    </EmbeddedResource>
  </ItemGroup>

</Project>
