using System.Runtime.Versioning;
using System.Security.Cryptography;

namespace FluentUI.Blazor.Community.Components;

/// <summary>
/// Provides AES-256 encryption and HMAC-based integrity protection for proof documents using keys derived from a master
/// key. Implements the IProofDocumentEncrypter interface for secure document encryption and decryption operations.
/// </summary>
/// <remarks>This class is not supported on browser platforms. It derives separate AES and HMAC keys from the
/// provided master key to ensure confidentiality and integrity of encrypted documents. Encrypted data includes an
/// initialization vector (IV), ciphertext, and HMAC for tamper detection. Use this class when strong symmetric
/// encryption and integrity verification are required for proof documents.</remarks>
[UnsupportedOSPlatform("browser")]
public sealed class AesProofDocumentEncrypter : IProofDocumentEncrypter
{
    /// <inheritdoc />
    public ValueTask<byte[]> EncryptAsync(ReadOnlyMemory<byte> data, ReadOnlyMemory<byte> key)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(key.Length, 32, nameof(key));
        DeriveKeys(key, out var aesKey, out var hmacKey);

        using var aes = Aes.Create();
        aes.Key = aesKey;
        aes.Mode = CipherMode.CBC;
        aes.Padding = PaddingMode.PKCS7;
        aes.GenerateIV();

        using var encryptor = aes.CreateEncryptor();
        var cipher = encryptor.TransformFinalBlock(data.ToArray(), 0, data.Length);

        var ivAndCipher = new byte[aes.IV.Length + cipher.Length];
        Buffer.BlockCopy(aes.IV, 0, ivAndCipher, 0, aes.IV.Length);
        Buffer.BlockCopy(cipher, 0, ivAndCipher, aes.IV.Length, cipher.Length);

        var hmac = ComputeHmac(ivAndCipher, hmacKey);

        var result = new byte[ivAndCipher.Length + hmac.Length];
        Buffer.BlockCopy(ivAndCipher, 0, result, 0, ivAndCipher.Length);
        Buffer.BlockCopy(hmac, 0, result, ivAndCipher.Length, hmac.Length);

        return ValueTask.FromResult(result);
    }

    /// <inheritdoc />
    public ValueTask<byte[]> DecryptAsync(ReadOnlyMemory<byte> data, ReadOnlyMemory<byte> key)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(key.Length, 32, nameof(key));

        DeriveKeys(key, out var aesKey, out var hmacKey);

        if (data.Length < 16 + 32)
        {
            throw new CryptographicException("Encrypted data is too short.");
        }

        var ivLength = 16;
        var hmacLength = 32;
        var ivAndCipherLength = data.Length - hmacLength;

        var ivAndCipher = data[..ivAndCipherLength].ToArray();
        var hmac = data.Slice(ivAndCipherLength, hmacLength).ToArray();

        var expectedHmac = ComputeHmac(ivAndCipher, hmacKey);

        if (!CryptographicOperations.FixedTimeEquals(hmac, expectedHmac))
        {
            throw new CryptographicException("HMAC validation failed.");
        }

        var iv = ivAndCipher.AsSpan(0, ivLength).ToArray();
        var cipher = ivAndCipher.AsSpan(ivLength).ToArray();

        using var aes = Aes.Create();
        aes.Key = aesKey;
        aes.IV = iv;
        aes.Mode = CipherMode.CBC;
        aes.Padding = PaddingMode.PKCS7;

        using var decryptor = aes.CreateDecryptor();
        return ValueTask.FromResult(decryptor.TransformFinalBlock(cipher, 0, cipher.Length));
    }

    /// <summary>
    /// Derives cryptographic keys for AES encryption and HMAC authentication from the specified master key using
    /// SHA-256.
    /// </summary>
    /// <remarks>The derived keys are generated by hashing the master key concatenated with distinct labels
    /// for AES and HMAC. This ensures that the resulting keys are unique for each purpose. The method does not validate
    /// the length or content of the master key; callers should ensure the master key meets their security
    /// requirements.</remarks>
    /// <param name="key">A read-only span of bytes representing the master key from which the AES and HMAC keys are derived.</param>
    /// <param name="aesKey">When this method returns, contains the derived AES encryption key as a byte array.</param>
    /// <param name="hmacKey">When this method returns, contains the derived HMAC authentication key as a byte array.</param>
    private static void DeriveKeys(ReadOnlyMemory<byte> key, out byte[] aesKey, out byte[] hmacKey)
    {
        aesKey = SHA256.HashData(Concat(key, "AES"u8));
        hmacKey = SHA256.HashData(Concat(key, "HMAC"u8));
    }

    /// <summary>
    /// Computes a HMAC-SHA256 hash for the specified data using the provided key.
    /// </summary>
    /// <remarks>The returned hash can be used to verify the integrity and authenticity of the data. The
    /// method allocates a new array for the hash result.</remarks>
    /// <param name="data">The input data to be hashed. The data is read as a sequence of bytes.</param>
    /// <param name="hmacKey">The secret key used to compute the HMAC. Must not be null and should be of sufficient length for security.</param>
    /// <returns>A byte array containing the computed HMAC-SHA256 hash.</returns>
    private static byte[] ComputeHmac(ReadOnlyMemory<byte> data, byte[] hmacKey)
    {
        using var hmac = new HMACSHA256(hmacKey);

        return hmac.ComputeHash(data.ToArray());
    }

    /// <summary>
    /// Concatenates the specified key and label byte sequences into a single byte array.
    /// </summary>
    /// <param name="key">A read-only memory region containing the key bytes to be placed at the beginning of the result array.</param>
    /// <param name="label">A read-only span containing the label bytes to be appended after the key in the result array.</param>
    /// <returns>A byte array consisting of the key bytes followed by the label bytes. The length of the array is the sum of the
    /// lengths of the key and label.</returns>
    private static byte[] Concat(ReadOnlyMemory<byte> key, ReadOnlySpan<byte> label)
    {
        var result = new byte[key.Length + label.Length];
        key.CopyTo(result);
        label.CopyTo(result.AsSpan(key.Length));

        return result;
    }
}
